### ISSUE TITLE
RunApp Error

### ISSUE THREAD

**Issue by jkaddis** [avucoh/DIVE#9] opened 2019-03-04 23:48 UTC
I ran shiny::runApp(system.file(package = "DIVE"), display.mode = "normal"), which initially yielded the following error:

Error in loadNamespace(name) : there is no package called ‘DT’

I installed and loaded the DT package, re-ran the command and ran into a different error:

Error: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'typedarray-0.1'; `directoryPath` = '/home/avu/R/x86_64-pc-linux-gnu-library/3.4/plotly/htmlwidgets/lib/typedarray'

**Comment by avucoh** [comment] 2019-03-06 01:54
Duplicate of #8

**Closed by avucoh** 2019-03-06 01:54 UTC
